config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :users, only: [:new, :index, :show, :edit, :update] do
   resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'

  end
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
  resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]

   end

  get 'home/about' => 'homes#about', as:'about'
  get '/search', to: 'searches#search'

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }

  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_one_attached :profile_image

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :correct_user, only: [:edit, :update]
  def index
  @user= current_user
  @users= User.all
  end

  def show
  @user = User.find(params[:id])
  @books = @user.books
  end

  def edit
  @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  if@user.update(user_params)
    flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(@user.id)
  else
      render :edit
  end
  end

   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
     @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= render "relationships/btn", user: user %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <td><%= render "relationships/btn", user: user %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class='container'>
<div class='row'>
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>

<% if @user.errors.any? %>
<%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
<% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
<% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>

  <div class="form-group">
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", class:"form-control", rows:"1"%>

  </div>

  <div class="form-group">
  <label for="inputImage">Image</label>
  <p><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></p>
  </div>

  <div class="form-group">
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class:"form-control", rows:"2"%>
  </div>

<%= f.submit "Update User", class: "btn btn-secondary" %>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<h2>User info</h2>
<%= render 'users/info', user: current_user %>
<%= render 'books/book', books: @books %>

</div>
<div class="col-md-8 offset-md-1">

<p id="notice"></p>
 <h2>Users</h2>
 <%= render 'index',users: @users %>
</div>

</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<h2>User info</h2>
<%= render 'info', user: current_user %>
<%= render 'books/book', books: @books %>
</div>

<div class="col-md-8 offset-md-1">
<h4>Books</h4>
 <%= render 'books/index',books: @books %>
</div>
</div>
</div>