config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :users, only: [:new, :index, :show, :edit, :update] do
   resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'

  end
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
  resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]

   end

  get 'home/about' => 'homes#about', as:'about'
  get '/search', to: 'searches#search'

  end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	 has_many :favorites, dependent: :destroy
	  has_many :book_comments, dependent: :destroy
	  has_many :book_tags, dependent: :destroy
    has_many :tags, through: :book_tags

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tags(savebook_tags)
    # 現在のユーザーの持っているskillを引っ張ってきている
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 今bookが持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
    old_tags = current_tags - savebook_tags
    # 今回保存されたものと現在の差を新しいタグとする。新しいタグは保存
    new_tags = savebook_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      book_tag = Tag.find_or_create_by(name:new_name)
      # 配列に保存
      self.tags << book_tag
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def new
   @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:tag_name].split(',')
  if@book.save
    @book.save_tags(tag_list)
    flash[:notice] = 'You have created book successfully.'
    redirect_to book_path(@book.id)
  else
    @books=Book.all
    @user= current_user
    render:index
  end
  end

  def index
    @book =Book.new
    @books=Book.all
    @user= current_user
   if params[:latest]
     @books = Book.latest
   elsif params[:old]
     @books = Book.old
   elsif params[:star_count]
     @books = Book.star_count
   else
     @books = Book.all
   end
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user= @book.user
  end

  def edit
  @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
  if @book.update(book_params)
    flash[:notice] = 'You have updated book successfully.'
    redirect_to book_path(@book)
  else
    render :edit
  end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star)
  end
end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    if @user != current_user
      redirect_to books_path
    end
  end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<h3 class="mt-3">New book</h3>

<%= form_with model: Book.new do |f| %>

  <div class="form-group">
  <label for="book_title">Title</label>
  <p><%= f.text_area :title, class:"form-control", rows:"1" %></p>
  </div>

  <div class="form-group">
  <label for="book_opinion">Opinion</label>
  <p><%= f.text_area :body, class:"form-control", rows:"2" %></p>
  </div>

  <div class="form-group">
   <%= f.label "Tag" %>
   <%= f.text_field :tag_name, class: 'form-control book_tag_name' %>
  </div>

 <div class="form-group row" id="star">
    <%#= f.label :star,'Rate ', class:'col-md-3 col-form-label' %>
    <%#= f.hidden_field :star, id: :review_star %>
  </div>

  <script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'book[star]',
    half: true,
  });
  </script>

  <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
<% books.each do |book| %>
<tr>
  <td>
   <%=link_to user_path(book.user) do %>

   <%=image_tag book.user.get_profile_image %>

   <% end %>
   </td>
  <td><%=link_to book.title ,book_path(book) %></td>
  <td><%= book.body %></td>
   <td>
          <% book.tags.each do |tag| %>
            <li style="list-style: none;"><%= link_to tag.name, search_path(content: tag.name, model:"tag", method: "perfect") %></li>
          <% end %>
        </td>
  <td>コメント数: <%= book.book_comments.count %></td>
  <td><%= l book.created_at %></td>
  <td><%= render 'favorites/favorites', book: book %></td>
    <td><%= render "books/static_star", book: book %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/books/_static_star.html.erb
 <td>
            <div id="star<%= book.id %>"></td>
             <script>
              $('#star<%= book.id %>').empty();
              $('#star<%= book.id %>').raty({
                 size      : 36,
                 starOff   : '<%= asset_path('star-off.png') %>',
                 starOn    : '<%= asset_path('star-on.png') %>',
                 starHalf    :'<%= asset_path('star-half.png') %>',
                 half      : true,
                 readOnly: true,
                 score: <%= book.star %>,
               });
             </script>
          </td>

app/views/books/_user.html.erb
<h2>User info</h2>
 <%=image_tag user.get_profile_image %>
 <table class="table">
  <tbody>
    <tr></tr>
    <tr>
    <th>name</th>
    <th><%= user.name %></th>
    </tr>
    <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
    </tr>
    </tbody>
    </table>

    <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <%end%>
    </div>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class='container'>
<div class='row'>
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
<% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

  <div class="form-group">
  <label for="inputTitle">Title</label>
  <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"Title"%>
  </div>

  <div class="form-group">
  <label for="inputBody">Opinion</label>
  <%= f.text_field :body, autofocus: true, id:"inputBody", placeholder:"Body"%>
  </div>

  <%= f.submit "Update Book" %>
<% end %>
 <td><%= link_to "Show", book_path %></td>
 <td><%= link_to "Back", books_path %></td>
</div>
</div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
<% end %>
  </ul>
<% end %>

<div class="row">
<div class="col-md-3">
<%= render 'books/user', user: @user %>
<%= render 'books/book', book: @book %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
 <p>
      <%= link_to '新しい順', books_path(latest: "true") %>
       |<%= link_to '古い順', books_path(old: "true") %>
       |<%= link_to '評価の高い順', books_path(star_count: "true") %>
      </p>
<%= render "books/index", books: @books %>
</div>
</div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<%= render 'books/user', user: @user %>
<%= render 'books/book', books: @books %>
</div>

<div class="col-md-8 offset-md-1">
<h4>Book detail</h4>
<table class="table">
<tr>
  <td>
   <%=link_to user_path(@book.user) do %>
   <%=image_tag @book.user.get_profile_image %>
   <p><%= @book.user.name %></p>
   <% end %>
   </td>

  <td><%=link_to @book.title ,book_path(@book) %></td>
  <td><%= @book.body %></td>
   <td>
            <% @book.tags.each do |tag| %>
              <li style="list-style: none;"><%= link_to tag.name, search_path(content: tag.name, model:"tag", method: "perfect") %></li>
            <% end %>
          </td>
  <td>コメント数: <%= @book.book_comments.count %></td>
 <td><%= render "static_star", book: @book %></td>

  <td><%= render 'favorites/favorites', book: @book %></td>

　<% if @book.user == current_user %>

  <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
  <td><%= link_to "Destroy", book_path(@book), class: "btn btn-sm btn-danger destroy", method: :delete,"data-confirm"=>"本当に消しますか?"  %></td>
  <% end %>
   </tr>
   </table>
    <div class="book-comments-index">
        <%= render "book_comments/index", book: @book %>
      </div>
      <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>